name: Draft Releases

on:
  push:
    branches:
      - main
      - dev
      - test
      - qa
  pull_request:
    branches:
      - dev
      - test
      - qa
      - main
    # Only following types are handled by the action, but one can default to all as well
    types: [closed]


permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # (Optional) GitHub Enterprise requires GHE_HOST variable set
      #- name: Set GHE_HOST
      #  run: |
      #    echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV
      - name: checkout
        id: checkout
        uses: actions/checkout@v3

      - name: semantic_version
        id: semantic_version
        run: |
          DEV="dev"
          TEST="test"
          QA="qa"
          PROD="main"

          if [ "$REF_NAME" = "$DEV" ]; then
              echo "value=alpha1" >> $GITHUB_OUTPUT
              echo "It's dev"
          elif [ "$REF_NAME" = "$TEST" ]; then
              echo "value=beta1" >> $GITHUB_OUTPUT
              echo "It's test"
          elif [ "$REF_NAME" = "$QA" ]; then
              echo "value=rc.1" >> $GITHUB_OUTPUT
              echo "It's qa"
          elif [ "$REF_NAME" = "$PROD" ]; then
              echo "It's prod"
          else
              echo "It's a feature"
          fi
        env:
          REF_NAME: ${{ github.ref_name }}
      - uses: release-drafter/release-drafter@v5
        if: github.event.pull_request.merged == true
        with:
          name: v$RESOLVED_VERSION${{ steps.semantic_version.outputs.value }}
          tag: v$RESOLVED_VERSION${{ steps.semantic_version.outputs.value }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}