name: Release Drafter

on:
  push:
    branches:
      - main
      - dev
      - test
      - qa
  pull_request:
    branches:
      - dev
      - test
      - qa
      - main
    # Only following types are handled by the action, but one can default to all as well
    types: [closed]


permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # (Optional) GitHub Enterprise requires GHE_HOST variable set
      #- name: Set GHE_HOST
      #  run: |
      #    echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV
      - name: checkout
        id: checkout
        uses: actions/checkout@v3

      - name: semantic_version
        id: semantic_version
        run: ./.github/workflows/helper.sh
        env:
          REF_NAME: ${{ github.ref_name }}
      - uses: release-drafter/release-drafter@v5
        if: github.event.pull_request.merged == true
        with:
          name: v$RESOLVED_VERSION${{ steps.semantic_version.outputs.value }}
          tag: v$RESOLVED_VERSION${{ steps.semantic_version.outputs.value }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}